### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by SomeAverageDev** [hariom282538/grafana_dashboard_screenshot#2]
hello,
Just to let you know,
I tried to run the module, and I had the "syntax" error below, looks like it is related to nodeJs version (I don't know much about nodeJS...) :

#npm start

```
> grafana_dashboard_screenshot@1.0.0 start /data/gfa-screenshot
> node server.js

/data/gfa-screenshot/app/controllers/grafana.controller.js:5
exports.capture = async function (req, res) {
                        ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at module.exports (/data/gfa-screenshot/app/routes/automation.routes.js:4:19)

npm ERR! Linux 3.10.0-1062.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! grafana_dashboard_screenshot@1.0.0 start: `node server.js`
npm ERR! Exit status 1

```

**Comment by hariom282538** [comment]
> hello,
> Just to let you know,
> I tried to run the module, and I had the "syntax" error below, looks like it is related to nodeJs version (I don't know much about nodeJS...) :
> 
> #npm start
> 
> ```
> > grafana_dashboard_screenshot@1.0.0 start /data/gfa-screenshot
> > node server.js
> 
> /data/gfa-screenshot/app/controllers/grafana.controller.js:5
> exports.capture = async function (req, res) {
>                         ^^^^^^^^
> 
> SyntaxError: Unexpected token function
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Module._compile (module.js:549:28)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at module.exports (/data/gfa-screenshot/app/routes/automation.routes.js:4:19)
> 
> npm ERR! Linux 3.10.0-1062.el7.x86_64
> npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
> npm ERR! node v6.17.1
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! grafana_dashboard_screenshot@1.0.0 start: `node server.js`
> npm ERR! Exit status 1
> ```

160

Async functions are not supported by Node versions older than version 7.6. 
Update NodeJS --> https://nodejs.org/en/download/
